// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABRQIbm3Dl4x8TKq_6Ht3PaNllH_8yuwo',
    appId: '1:912983858748:web:5a38bd0f75ce63190bad39',
    messagingSenderId: '912983858748',
    projectId: 'keen-tokenizer-400311',
    authDomain: 'keen-tokenizer-400311.firebaseapp.com',
    storageBucket: 'keen-tokenizer-400311.appspot.com',
    measurementId: 'G-MR3HM0K20Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFliG30yK5Kni1TDp8R0aCSxN-7tDyqg8',
    appId: '1:912983858748:android:ba497fbe4464b2a60bad39',
    messagingSenderId: '912983858748',
    projectId: 'keen-tokenizer-400311',
    storageBucket: 'keen-tokenizer-400311.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeBNy7o_fnEeG33lvV9vzfCi6TDKQDwZI',
    appId: '1:912983858748:ios:3c943b5b967df0220bad39',
    messagingSenderId: '912983858748',
    projectId: 'keen-tokenizer-400311',
    storageBucket: 'keen-tokenizer-400311.appspot.com',
    iosBundleId: 'com.example.benjiVendor',
  );
}
